version: "3.1" 

services:
  db:
    image: mysql  
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=db
      - MYSQL_USER=mati
      - MYSQL_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: db-ticmas
    expose:
      - 3310
    network_mode: host
volumes:
  mysql-data:  


# docker compose up