version: "3.1" 

services:
  db:
    image: mysql  
    ports:
      - "3310:3310"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:  


# docker compose up